name: Build APK
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '18.x'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.0

      - run: flutter pub get

      # - run: flutter analyze TODO: enable after fixing the issues in code

      - run: flutter test

      - name: Build Android Packages
        run: flutter build apk

      - name: Upload Android debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android_debug
          path: "build/app/outputs/flutter-apk/app-release.apk"

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: android_release

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "/"
          name: Release Apk
          token: ${{ secrets.GITHUB_TOKEN }}