name: Build APK
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '18.x'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.0

      - run: flutter pub get

      # - run: flutter analyze TODO: enable after fixing the issues in code

      - run: flutter test

      - name: Build Android Packages
        run: flutter build apk

      - name: Upload Android debug artifacts
        if: ${{ env.BUILD_MODE == 'debug' }}
        uses: actions/upload-artifact@v1
        with:
          name: android_debug
          path: "build/app/outputs/flutter-apk/app-release.apk"